# Generated by Django 3.0 on 2020-01-04 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.TextField(max_length=50)),
                ('desc', models.TextField(max_length=300)),
                ('pub_Date', models.DateField()),
            ],
        ),
    ]
